// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFVNpv4NkPsRfJx3y9N-2EO2f1hM-Mv0',
    appId: '1:193041067975:web:c2a0eaffcc8426747773e2',
    messagingSenderId: '193041067975',
    projectId: 'namemaker-f51c5',
    authDomain: 'namemaker-f51c5.firebaseapp.com',
    storageBucket: 'namemaker-f51c5.appspot.com',
    measurementId: 'G-M1JSPPPNFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbHEyPalHyAnu6yyR43gxFAyiw1SMYqwQ',
    appId: '1:193041067975:android:f16aa7fc17b129c27773e2',
    messagingSenderId: '193041067975',
    projectId: 'namemaker-f51c5',
    storageBucket: 'namemaker-f51c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFeDkZrVMYyTRV9VOBKyhd_p_MGFhSl5g',
    appId: '1:193041067975:ios:b03c21372b2bf6067773e2',
    messagingSenderId: '193041067975',
    projectId: 'namemaker-f51c5',
    storageBucket: 'namemaker-f51c5.appspot.com',
    iosBundleId: 'com.example.nameMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFeDkZrVMYyTRV9VOBKyhd_p_MGFhSl5g',
    appId: '1:193041067975:ios:ae4102801d1246307773e2',
    messagingSenderId: '193041067975',
    projectId: 'namemaker-f51c5',
    storageBucket: 'namemaker-f51c5.appspot.com',
    iosBundleId: 'com.example.nameMaker.RunnerTests',
  );
}
